# for making changes to pods, update this deployment file & apply the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec: # defines the desired state of the object
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq # looks for pod labelled rabbitmq
  template: # for creating new pods 
    metadata:
      labels:
        app: rabbitmq # defines the pod created 
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 # expose 5672 to the container
        - containerPort: 15672 # expose 15672 to the container