# for making changes to pods, update this deployment file & apply the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec: # defines the desired state of the object
  replicas: 1
  selector:
    matchLabels:
      app: zipkin # looks for pod labelled zipkin
  template: # for creating new pods 
    metadata:
      labels:
        app: zipkin # defines the pod created 
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411 # expose 9411 to the container